---
- name: Ensure dotfiles repository is cloned locally.
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_repo_local_destination }}"
    version: "{{ dotfiles_repo_version }}"
    accept_hostkey: "{{ dotfiles_repo_accept_hostkey }}"
  become: false

- name: Link dotfiles using stow
  command: "stow --adopt . && git restore . && stow --restow ."
  args:
    chdir: "{{ dotfiles_repo_local_destination }}"