---
- name: Ensure dotfiles repository is cloned locally.
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_repo_local_destination }}"
    version: "{{ dotfiles_repo_version }}"
    accept_hostkey: "{{ dotfiles_repo_accept_hostkey }}"
  become: false

- name: Ensure dotfiles repository is up to date
  shell: "git pull"
  args:
    chdir: "{{ dotfiles_repo_local_destination }}"

- name: Ensure .config directory exists in the $HOME directory
  file:
    path: $HOME/.config
    state: directory
    mode: '0755'

- name: Link dotfiles using stow
  shell: "stow --adopt . && git restore . && stow --restow ."
  args:
    chdir: "{{ dotfiles_repo_local_destination }}"
