---
- name: Ensure dotfiles repository is cloned locally.
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_repo_local_destination }}"
    version: "{{ dotfiles_repo_version }}"
    accept_hostkey: "{{ dotfiles_repo_accept_hostkey }}"
  become: false

- name: Pull changes from the remote
  command: "cd {{ dotfiles_repo_local_destination }} && git pull origin"

- name: Link dotfiles using stow
  command: "cd {{ dotfiles_repo_local_destination }} && stow --adopt . && git restore . && stow --restow ."