---
# List of repositories to clone/update
- name: Clone or update git repositories
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    version: "{{ item.version | default('main') }}"
    update: yes
    force: no
  loop: "{{ git_repositories }}"
  ignore_errors: true
