---  
- name: Test if N is available
  command: which n
  register: n_path
  ignore_errors: true

- name: Store N path if present
  set_fact:
    n_bin_path: "{{ n_path.stdout }}"
  when: n_path.rc == 0